// Exercise registry — all training configurations in one place.
// Shared TTS maps (number clips are reused across exercises).

const TRAINER_TTS = '../trainer_tts';
const HYOID_TTS = '../hyoid_tts';

const TRAINER_MAP = {
  '准备好': 'ready', '开始': 'start', '继续': 'continue',
  '走到墙边，准备靠墙天使': 'go_to_wall',
  '要点：腰贴墙，后脑勺贴墙，收下巴，手臂全程贴墙': 'form_tips',
  '该做运动了': 'time_to_move', '训练完成，做得好': 'done_good',
  '今日目标已完成': 'target_done', '过半了': 'half',
  '坚持': 'keep_going', '快完了': 'almost',
};

const HYOID_MAP = {
  '准备': 'prepare', '开始': 'start', '开始保持': 'hold_start',
  '休息': 'rest', '过半了': 'halfway', '过半了，继续': 'halfway_go',
  '训练完成': 'done', '暂停': 'pause', '继续': 'resume',
};

export const exercises = [
  {
    id: 'wall_angel',
    name: '靠墙天使',
    subtitle: 'Wall Angel',
    category: '头前倾矫正',
    categoryTag: 'posture',
    daily: true,
    description: '脚离墙30cm，腰/背/头贴墙，双臂贴墙做W-Y上下滑动。',
    tips: '腰贴墙 · 后脑勺贴墙 · 收下巴 · 手臂全程贴墙 · 膝盖微屈',
    mode: 'counted_reps',
    defaults: { sets: 3, reps: 20, tempo: 1.5, rest: 30, prepSec: 12 },
    ttsDir: TRAINER_TTS,
    ttsMap: TRAINER_MAP,
    hasSetAnnounce: true,
    hasBGM: true,
    hasScheduler: true,
    dailyTarget: 360,
    video: null,
    images: [],
  },
  {
    id: 'shaker_iso',
    name: 'Shaker 练习 · 抬头不动',
    subtitle: '仰卧等长保持',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    daily: true,
    description: '仰卧平躺，抬头看脚尖方向，保持不动。',
    tips: '不要抬肩 · 只抬头 · 看向脚尖方向',
    mode: 'timed_hold',
    defaults: { sets: 3, holdSec: 30, rest: 60, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/shaker.mp4',
    images: [],
  },
  {
    id: 'shaker_dyn',
    name: 'Shaker 练习 · 连续抬放',
    subtitle: '仰卧动态',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    daily: true,
    description: '仰卧平躺，连续抬头放下。',
    tips: '每次抬头看脚尖 · 控制速度 · 不要用惯性',
    mode: 'counted_reps',
    defaults: { sets: 1, reps: 30, tempo: 3, rest: 0, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: false,
    hasBGM: false,
    video: '../videos/shaker.mp4',
    images: [],
  },
  {
    id: 'subman_push',
    name: '下颌推压',
    subtitle: '舌骨上肌群抗阻',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    daily: true,
    description: '拇指顶住下巴，舌头顶上颚，同时下巴向下用力抵抗拇指。',
    tips: '舌顶上颚 · 下巴向下用力 · 拇指抵抗',
    mode: 'timed_hold',
    defaults: { sets: 10, holdSec: 10, rest: 5, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/suprahyoid.mp4',
    images: [],
  },
  {
    id: 'fesm',
    name: 'FESM 前额等长抗阻',
    subtitle: '颏舌骨肌强化',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    daily: true,
    description: '手掌抵住前额，收下巴的同时头向前用力，手抵住不动。',
    tips: '收下巴 · 头前推 · 手稳住不动 · 保持5秒',
    mode: 'timed_reps',
    defaults: { sets: 5, repsPerSet: 10, holdSec: 5, restRep: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/ctar.mp4',
    images: [],
  },
  {
    id: 'chin_tuck',
    name: 'Chin Tuck 收下巴',
    subtitle: '深层颈屈肌',
    category: '姿势矫正',
    categoryTag: 'posture',
    daily: true,
    description: '坐直或站立，收下巴向后平移（做双下巴），保持5秒。',
    tips: '水平后缩 · 不要低头 · 想象头顶被线提起',
    mode: 'timed_reps',
    defaults: { sets: 1, repsPerSet: 20, holdSec: 5, restRep: 2, rest: 0, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: false,
    hasBGM: false,
    video: '../videos/chin_tuck.mp4',
    images: [],
  },
  {
    id: 'mewing',
    name: 'Mewing 舌位训练',
    subtitle: '全天习惯养成',
    category: '姿势矫正',
    categoryTag: 'posture',
    daily: true,
    description: '整个舌面贴住上颚，嘴唇轻闭，用鼻子呼吸。这是全天候习惯，不需要计时。',
    tips: '舌尖抵上颚齿龈后方 · 整个舌面上贴 · 鼻呼吸',
    mode: null,
    defaults: {},
    ttsDir: null,
    ttsMap: null,
    hasBGM: false,
    video: '../videos/mewing.mp4',
    images: [],
  },
  {
    id: 'jawline',
    name: '颏下综合训练',
    subtitle: '辅助训练',
    category: '辅助训练',
    categoryTag: 'auxiliary',
    daily: true,
    description: '辅助性颏下区域训练，可根据自身情况选做。',
    tips: '',
    mode: null,
    defaults: {},
    ttsDir: null,
    ttsMap: null,
    hasBGM: false,
    video: '../videos/jawline.mp4',
    images: [],
  },
  {
    id: 'pelvic_breath',
    name: '俯卧位腰椎呼吸',
    subtitle: '骨盆前倾矫正 · 热身',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    daily: false,
    description: '趴在桌边或垫子上，用鼻子深吸气，将气息引导到腰椎后方，感受腰部向后膨胀。',
    tips: '趴稳后放松全身 · 吸气时腰部后侧膨起 · 呼气缓慢 · 保持2分钟',
    mode: 'timed_hold',
    defaults: { sets: 1, holdSec: 120, rest: 0, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: false,
    hasBGM: false,
    video: null,
    images: [],
  },
  {
    id: 'pelvic_tilt',
    name: '仰卧屈膝骨盆后倾',
    subtitle: '学会骨盆后倾发力',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    daily: false,
    description: '仰卧屈膝，脚踩地，收紧腹部将尾骨向脚跟方向卷起，腰部贴紧地面。',
    tips: '尾骨向脚跟方向靠近 · 腰部贴地 · 不要用腿发力 · 感受下腹收缩',
    mode: 'counted_reps',
    defaults: { sets: 1, reps: 15, tempo: 3, rest: 0, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: false,
    hasBGM: false,
    video: null,
    images: [],
  },
  {
    id: 'hip_flexor_stretch',
    name: '单膝跪位髋伸展',
    subtitle: '拉伸髂腰肌',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    daily: false,
    description: '单膝跪地，前脚屈膝90°，收紧核心，身体前移拉伸后腿髂腰肌。左右交替。',
    tips: '收紧核心 · 身体前移 · 后腿前侧有拉伸感 · 奇数组左腿，偶数组右腿',
    mode: 'timed_hold',
    defaults: { sets: 6, holdSec: 15, rest: 10, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: [],
  },
  {
    id: 'single_leg_lower',
    name: '仰卧单腿下落',
    subtitle: '核心控制训练',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    daily: false,
    description: '仰卧屈膝，一条腿慢慢伸直下落，保持骨盆稳定不动，再收回。左右交替。',
    tips: '手放髂骨前缘监控骨盆 · 骨盆不能晃动 · 慢下慢收 · 奇数组左腿，偶数组右腿',
    mode: 'counted_reps',
    defaults: { sets: 6, reps: 10, tempo: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: [],
  },
  {
    id: 'single_glute_bridge',
    name: '单腿臀桥',
    subtitle: '臀肌激活',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    daily: false,
    description: '仰卧屈膝，一条腿伸直抬起，用另一条腿的臀肌发力顶髋。左右交替。',
    tips: '臀肌主动收缩 · 顶髋时身体成一条线 · 不要用腰发力 · 奇数组左腿，偶数组右腿',
    mode: 'counted_reps',
    defaults: { sets: 6, reps: 15, tempo: 2, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: [],
  },
  {
    id: 'single_leg_deadlift',
    name: '简化版单腿硬拉',
    subtitle: '后链整合训练',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    daily: false,
    description: '单腿站立，另一条腿向后伸，躯干前倾至与地面平行，再回到站立。左右交替。',
    tips: '脊柱保持直线 · 屈髋到120° · 核心收紧 · 奇数组左腿，偶数组右腿',
    mode: 'counted_reps',
    defaults: { sets: 6, reps: 15, tempo: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: [],
  },
  {
    id: 'band_back',
    name: '弹力带练背',
    subtitle: '圆肩驼背矫正 · 约20分钟',
    category: '圆肩驼背矫正',
    categoryTag: 'posture',
    daily: false,
    description: '弹力带背部+肩后束训练，改善圆肩驼背。跟练视频约20分钟，一次打勾代表全套完成。',
    tips: '① 胸小肌拉伸（热身）\n② 肩关节环绕（热身）\n③ 弹力带飞鸟 × 4组\n④ 窄距高位下拉 × 4组\n⑤ 宽距坐姿划船 × 4组\n⑥ 绳索面拉 × 4组\n⑦ 背部拉伸（放松）',
    mode: null,
    defaults: {},
    ttsDir: null,
    ttsMap: null,
    hasBGM: false,
    video: null,
    externalVideo: 'https://www.xiaohongshu.com/discovery/item/67d7cd85000000000b03a6c7',
    images: [],
  },
];

export function getExercise(id) {
  return exercises.find(e => e.id === id);
}

export function getTrainableExercises() {
  return exercises.filter(e => e.mode !== null);
}

export function getDailyExercises() {
  return exercises.filter(e => e.daily !== false);
}
