// Exercise registry — all training configurations in one place.
// Shared TTS maps (number clips are reused across exercises).

const TRAINER_TTS = '../trainer_tts';
const HYOID_TTS = '../hyoid_tts';

const TRAINER_MAP = {
  '准备好': 'ready', '开始': 'start', '继续': 'continue',
  '走到墙边，准备靠墙天使': 'go_to_wall',
  '要点：腰贴墙，后脑勺贴墙，收下巴，手臂全程贴墙': 'form_tips',
  '该做运动了': 'time_to_move', '训练完成，做得好': 'done_good',
  '今日目标已完成': 'target_done', '过半了': 'half',
  '坚持': 'keep_going', '快完了': 'almost',
};

const HYOID_MAP = {
  '准备': 'prepare', '开始': 'start', '开始保持': 'hold_start',
  '休息': 'rest', '过半了': 'halfway', '过半了，继续': 'halfway_go',
  '训练完成': 'done', '暂停': 'pause', '继续': 'resume',
};

export const exercises = [
  {
    id: 'wall_angel',
    name: '靠墙天使',
    subtitle: 'Wall Angel',
    category: '头前倾矫正',
    categoryTag: 'posture',
    scene: '站立 · 靠墙',
    daily: true,
    description: '脚离墙约30cm，腰/背/后脑勺贴墙，收下巴，双臂贴墙做W→Y上下滑动，每次20个为一组。',
    tips: '腰贴墙（可塞不进一根手指） · 后脑勺贴墙 · 收下巴 · 手臂和手背全程贴墙 · 膝盖微屈',
    details: '综合矫正头前倾、圆肩和胸椎后凸。W-Y滑动同时激活下斜方肌、菱形肌和前锯肌，强化背部维持正确姿势的肌群。贴墙是为了给你一个参考面，让你知道"正确姿势"是什么感觉。如果手臂贴不了墙说明胸肌太紧，需要先拉伸。',
    mode: 'counted_reps',
    defaults: { sets: 3, reps: 20, tempo: 1.5, rest: 30, prepSec: 12 },
    ttsDir: TRAINER_TTS,
    ttsMap: TRAINER_MAP,
    hasSetAnnounce: true,
    hasBGM: true,
    hasScheduler: true,
    dailyTarget: 180,
    video: null,
    images: ['../images/wall_angel_demo.jpg'],
  },
  {
    id: 'chin_tuck',
    name: 'Chin Tuck 收下巴',
    subtitle: '深层颈屈肌',
    category: '头前倾矫正',
    categoryTag: 'posture',
    scene: '坐姿 · 随时',
    daily: true,
    description: '坐直或站立，目视前方，把下巴往后收（想象有人推你下巴），做出"双下巴"的感觉，保持5秒后放松，重复20次。',
    tips: '水平后缩，不是低头 · 做出双下巴感觉 · 想象头顶被线提起 · 颈后侧应有轻微挤压感',
    details: '目标：深层颈屈肌（头长肌、颈长肌）。纠正头前倾姿势，增大CVA（颅椎角）。4周矫正运动RCT(Titcomb 2023)：CVA增加+4.4°。可间接改善下颌后缩外观。毛巾辅助版：仰卧时将毛巾卷垫在颈后做收下巴，可加强训练效果。',
    mode: 'timed_reps',
    defaults: { sets: 1, repsPerSet: 20, holdSec: 5, restRep: 2, rest: 0, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: false,
    hasBGM: false,
    video: '../videos/chin_tuck.mp4',
    externalVideo: 'https://www.youtube.com/watch?v=1v9e8PdmqEI',
    images: ['../images/chin_tuck_demo.jpg'],
  },
  {
    id: 'subman_push',
    name: '下颌推压',
    subtitle: '舌骨上肌群抗阻',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    scene: '坐姿 · 随时',
    daily: true,
    description: '拇指顶住下巴下方软组织区域（颏下三角），舌头整面用力推上颚，拇指同时给反向阻力，保持10秒。',
    tips: '拇指放颏下三角（下巴正下方软肉处） · 舌头整面顶上颚 · 拇指向上给阻力 · 保持10秒后放松',
    details: '对舌骨上肌群的选择性激活是Shaker练习的3.9倍(Yano 2021)，同时胸锁乳突肌干扰显著更低。8周抗阻训练后舌骨上肌最大激活显著增加(Sze 2020 RCT)，效果优于仰卧抬头。',
    mode: 'timed_hold',
    defaults: { sets: 10, holdSec: 10, rest: 5, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/subman_push_demo.jpg'],
  },
  {
    id: 'fesm',
    name: 'FESM 前额等长抗阻',
    subtitle: '颏舌骨肌强化',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    scene: '坐姿 · 随时',
    daily: true,
    description: '坐正或站立，手掌抵住前额，头往前用力推但手不让头动（等长收缩），同时做收下巴动作，保持5秒后放松。每组10次，共5组，每天50次。',
    tips: '收下巴 · 头前推 · 手稳住不动 · 等长收缩（头不能真的动） · 每天累计50次',
    details: '目标：颏舌骨肌。前额抵抗时颏舌骨肌通过协同收缩被间接激活，比直接训练更安全有效。8周后颏舌骨肌面积增长12.5%，吞咽能力改善(Fujishima 2024)。训练前做一次FESM即可降低当次进食误吸风险。',
    mode: 'timed_reps',
    defaults: { sets: 5, repsPerSet: 10, holdSec: 5, restRep: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/fesm_demo.jpg'],
  },
  {
    id: 'mewing',
    name: 'Mewing 舌位训练',
    subtitle: '全天习惯养成 · 每日10次',
    category: '舌骨肌群',
    categoryTag: 'hyoid',
    scene: '坐姿 · 随时',
    daily: true,
    dailyCheckTarget: 10,
    description: '舌尖放在上门牙后方牙龈处（不碰牙齿），舌头整面（包括后1/3）贴紧上颚，嘴唇自然闭合，用鼻子呼吸。全天保持。',
    tips: '舌尖不碰牙齿，放牙龈处 · 重点是后1/3也要贴上去 · 嘴唇轻闭 · 鼻呼吸 · 吞咽时注意舌头是否自然上推',
    details: '通过舌体持续贴合硬腭施力，促进鼻呼吸，减少口呼吸引起的颌面退缩。关键是后1/3的舌面也要贴上，很多人只贴了前半段。OMFT研究显示低舌位改善率可达76%，鼻呼吸显著改善。注意：成人骨骼改变证据不足，但软组织改善有依据。',
    mode: null,
    defaults: {},
    ttsDir: null,
    ttsMap: null,
    hasBGM: false,
    video: null,
    images: ['../images/mewing_demo.jpg'],
  },
  {
    id: 'soft_palate_lift',
    name: '软腭抬升',
    subtitle: '发"啊"抬悬雍垂',
    category: '口咽抗鼾',
    categoryTag: 'airway',
    scene: '坐姿 · 随时',
    daily: true,
    description: '张嘴发出持续的"啊——"声，感觉软腭（口腔后上方）和悬雍垂（小舌头）向上抬起。保持3秒后放松，重复10次。',
    tips: '照镜子看小舌头有没有上抬 · 声音从喉咙深处发出 · 不要只张嘴，要感觉软腭收缩 · 可交替"啊"和"ng"鼻音',
    details: '目标：腭咽肌、悬雍垂肌。软腭松弛是打鼾的直接原因——呼气时软腭振动产生鼾声。系统综述显示口咽训练可将鼾声强度降低51%、打鼾时长减少31%。交替发"啊"和"ng"可以训练腭咽闭合-开放的完整运动范围。',
    mode: 'timed_reps',
    defaults: { sets: 2, repsPerSet: 10, holdSec: 3, restRep: 2, rest: 10, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/soft_palate_lift_demo.jpg'],
  },
  {
    id: 'dry_gargle',
    name: '无水漱口',
    subtitle: '咽后壁训练',
    category: '口咽抗鼾',
    categoryTag: 'airway',
    scene: '坐姿 · 随时',
    daily: true,
    description: '模拟漱口动作但口中不含水，发出"咕噜咕噜"声，感觉咽后壁在收缩。每次持续60秒，共3组。',
    tips: '不含水，做漱口动作 · 声音越响说明咽壁收缩越有力 · 可配合仰头增加强度 · 初期咽壁会酸，正常',
    details: '来源：Guimarães 2009经典RCT。目标：上/中/下咽缩肌。这些肌肉构成咽后壁，睡眠时松弛导致气道塌陷。该RCT中受试者每天做200次无水漱口，3个月后AHI从22.4降至13.7（p<0.01）。这是证据最强的单项口咽训练动作之一。',
    mode: 'timed_hold',
    defaults: { sets: 3, holdSec: 60, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/dry_gargle_demo.jpg'],
  },
  {
    id: 'vowel_exercise',
    name: '元音发声',
    subtitle: 'a-e-i-o-u 口咽协调',
    category: '口咽抗鼾',
    categoryTag: 'airway',
    scene: '坐姿 · 随时',
    daily: true,
    description: '依次发出 a—e—i—o—u 五个元音，每个拉长3秒，夸张张嘴变化口型。做完一轮5个元音算1次，共重复5次。',
    tips: '口型要夸张 · 每个元音拉长3秒 · "a"大张嘴、"i"咧嘴、"o/u"嘟嘴 · 间歇性发声比连续发声激活更强',
    details: '来源：Guimarães 2009经典RCT。发元音时口咽部多组肌群协调运动：a激活软腭和咽壁，e/i激活舌中后部和咽侧壁，o/u激活口轮匝肌和颊肌。间歇性发声（元音之间停顿）对肌肉激活强于连续发声。',
    mode: 'timed_reps',
    defaults: { sets: 3, repsPerSet: 5, holdSec: 15, restRep: 3, rest: 10, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/vowel_exercise_demo.jpg'],
  },
  {
    id: 'cheek_suction',
    name: '颊肌吸吮',
    subtitle: '颊肌收缩训练',
    category: '口咽抗鼾',
    categoryTag: 'airway',
    scene: '坐姿 · 随时',
    daily: true,
    description: '嘴唇闭合不动，单纯用颊肌（腮帮子）向内吸，做出"吸面条"的脸型，保持5秒后放松。',
    tips: '嘴唇不要动，只用脸颊发力 · 两侧面颊应明显凹进去 · 不要用嘴唇吸 · 感受腮帮子内侧肌肉发力',
    details: '来源：Guimarães 2009经典RCT。目标：颊肌（buccinator）。颊肌位于口咽侧壁外侧，收缩时可稳定咽侧壁，减少睡眠时的侧方塌陷。训练方法是只用颊肌做吸吮动作，嘴唇保持不动，以隔离颊肌收缩。',
    mode: 'timed_reps',
    defaults: { sets: 2, repsPerSet: 10, holdSec: 5, restRep: 2, rest: 10, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/cheek_suction_demo.jpg'],
  },
  {
    id: 'straw_blow',
    name: '吸管吹气',
    subtitle: '软腭阻力训练',
    category: '口咽抗鼾',
    categoryTag: 'airway',
    scene: '坐姿 · 需要吸管',
    daily: true,
    description: '将吸管含在嘴里，用力向吸管内吹气8秒。可以用手指堵住吸管另一端增加阻力。',
    tips: '嘴唇紧密包住吸管 · 吹气时感觉腹部和软腭都在用力 · 堵住另一端可增加强度 · 不要鼓腮，力量从腹部来',
    details: '目标：软腭肌群+呼气肌。吹气时软腭必须上抬封闭鼻咽才能让气流从嘴出，是功能性软腭训练。阻力呼气还能锻炼呼气肌，改善气道正压维持能力。NHS Torbay口咽训练方案推荐动作。进阶：换更细的吸管或用水中吹泡泡增加阻力。',
    mode: 'timed_reps',
    defaults: { sets: 2, repsPerSet: 10, holdSec: 8, restRep: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: null,
    images: ['../images/straw_blow_demo.jpg'],
  },
  {
    id: 'serratus_wall_push',
    name: '前锯肌墙推',
    subtitle: 'Serratus Wall Push',
    category: '圆肩驼背矫正',
    categoryTag: 'posture',
    scene: '站立 · 靠墙',
    daily: true,
    description: '面对墙壁站立，双手撑墙与肩同宽。手臂伸直后，继续用力把墙"推远"——感觉肩胛骨向前滑出，上背微微拱起，然后缓慢回到起始位。',
    tips: '推到底时肩胛骨前伸（不是手臂弯曲推） · 腋下前侧发力 · 上背微拱 · 不要耸肩 · 核心收紧',
    details: '目标：前锯肌。前锯肌负责将肩胛骨"贴住"胸廓，防止翼状肩胛。圆肩驼背时前锯肌往往无力，导致肩胛骨不稳定。墙推Plus是最安全的入门版本，进阶可改为桌面或地面俯卧撑Plus。',
    mode: 'counted_reps',
    defaults: { sets: 2, reps: 12, tempo: 4, rest: 40, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/serratus_wall_push.mp4',
    externalVideo: 'https://www.youtube.com/watch?v=_UPtlY7K4pQ',
    images: [],
  },
  {
    id: 'y_raise',
    name: 'Y Raise',
    subtitle: '下斜方肌激活',
    category: '圆肩驼背矫正',
    categoryTag: 'posture',
    scene: '俯卧 · 趴着',
    daily: true,
    description: '俯卧趴在地上或床边，双臂伸直呈Y字形（大拇指朝上）。肩胛骨向下向内收，将手臂缓慢抬离地面，顶点停2秒，再缓慢放下。',
    tips: '不要耸肩（最重要） · 肩胛骨向"下+内"走 · 顶点停2秒 · 手不是重点，感受背部发力 · 幅度不用大',
    details: '目标：下斜方肌。下斜方肌负责将肩膀"往下稳定"，防止上斜方肌代偿耸肩。圆肩驼背时下斜方肌通常被抑制，靠墙天使无法精准激活它。Y Raise是定点激活动作，同时也能激活前锯肌。正确感觉是腋下后侧（靠背部）发力，而非手臂酸。',
    mode: 'counted_reps',
    defaults: { sets: 2, reps: 10, tempo: 5, rest: 50, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/y_raise.mp4',
    externalVideo: 'https://www.youtube.com/watch?v=NJ2S63elQsQ',
    images: [],
  },
  {
    id: 'band_back',
    name: '弹力带练背',
    subtitle: '圆肩驼背矫正 · 约20分钟',
    category: '圆肩驼背矫正',
    categoryTag: 'posture',
    scene: '跟练视频',
    daily: false,
    estimatedMinutes: 20,
    description: '弹力带背部+肩后束训练，改善圆肩驼背。跟练视频约20分钟，一次打勾代表全套完成。',
    tips: '① 胸小肌拉伸（热身）\n② 肩关节环绕（热身）\n③ 弹力带飞鸟 × 4组\n④ 窄距高位下拉 × 4组\n⑤ 宽距坐姿划船 × 4组\n⑥ 绳索面拉 × 4组\n⑦ 背部拉伸（放松）',
    mode: null,
    defaults: {},
    ttsDir: null,
    ttsMap: null,
    hasBGM: false,
    video: null,
    externalVideo: 'http://xhslink.com/o/7puF65kMV9g',
    images: [],
  },
  {
    id: 'pelvic_tilt',
    name: '仰卧屈膝骨盆后倾',
    subtitle: '学会骨盆后倾发力',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    scene: '仰卧',
    daily: false,
    description: '仰卧屈膝脚踩地，收紧腹部，将尾骨向脚跟方向卷起（骨盆后倾），腰部完全贴紧地面。做15次。',
    tips: '尾骨向脚跟方向靠近 · 腰部贴地 · 不要用腿发力 · 感受下腹收缩 · 动作幅度不大但要精准',
    details: '学会骨盆后倾的发力模式。骨盆前倾的人往往不会主动后倾，这个动作就是训练这个能力。关键是用下腹部发力，不是用臀部或腿。可以把手放在腰下面检查——做对了手会被腰压住。',
    mode: 'counted_reps',
    defaults: { sets: 1, reps: 15, tempo: 3, rest: 0, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: false,
    hasBGM: false,
    video: '../videos/pelvic_tilt.mp4',
    images: [],
  },
  {
    id: 'single_leg_lower',
    name: '仰卧单腿下落',
    subtitle: '核心控制训练',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    scene: '仰卧',
    daily: false,
    alternating: 'legs',
    description: '仰卧屈膝，双腿屈髋90°，一条腿慢慢伸直向下放，保持骨盆完全稳定不动，再慢慢收回。左右交替，每侧10次×3组。',
    tips: '手放髂骨前缘监控骨盆 · 骨盆绝对不能晃动 · 慢下慢收 · 如果骨盆动了说明腿放太低',
    details: '核心控制训练。这个动作的关键不是腿放多低，而是在腿下落过程中骨盆保持稳定。手放在两侧髂骨前缘（胯骨最突出的地方），一旦感觉到骨盆在转就停，说明腿放太低了。随着核心力量增强，腿可以逐渐放更低。',
    mode: 'counted_reps',
    defaults: { sets: 6, reps: 10, tempo: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/single_leg_lower.mp4',
    images: [],
  },
  {
    id: 'single_glute_bridge',
    name: '单腿臀桥',
    subtitle: '臀肌激活',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    scene: '仰卧',
    daily: false,
    alternating: 'legs',
    description: '仰卧屈膝，一条腿伸直抬起，用另一条腿的臀肌发力顶髋，顶到最高点时身体从肩到膝成一条直线。左右交替，每侧15次×3组。',
    tips: '臀肌主动收缩 · 顶到最高点停一下 · 不要用腰代偿 · 支撑腿的臀部应有明显发力感',
    details: '激活臀大肌。骨盆前倾的人往往臀肌无力，被髂腰肌拉着走。单腿版比双腿臀桥难度更高，能更好地激活单侧臀肌。如果做的时候腰先酸说明在用腰代偿，需要降低高度或回到双腿版。',
    mode: 'counted_reps',
    defaults: { sets: 6, reps: 15, tempo: 2, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/single_glute_bridge.mp4',
    images: [],
  },
  {
    id: 'single_leg_deadlift',
    name: '简化版单腿硬拉',
    subtitle: '后链整合训练',
    category: '骨盆前倾矫正',
    categoryTag: 'auxiliary',
    scene: '站立',
    daily: false,
    alternating: 'legs',
    description: '单腿站立（另一只脚可以轻点地辅助平衡），屈髋向后向下，脊柱保持直线，臀肌收缩站起。左右交替，每侧15次×3组。',
    tips: '脊柱全程保持直线 · 核心收紧 · 感受臀肌和腘绳肌发力 · 可以扶墙辅助平衡',
    details: '后链整合训练，同时训练臀肌、腘绳肌和核心稳定性。这是6个动作中最难的一个。简化版允许另一只脚轻点地面辅助平衡，不需要完全单腿悬空。关键是屈髋而不是弯腰——脊柱始终保持中立位。',
    mode: 'counted_reps',
    defaults: { sets: 6, reps: 15, tempo: 3, rest: 15, prepSec: 5 },
    ttsDir: HYOID_TTS,
    ttsMap: HYOID_MAP,
    hasSetAnnounce: true,
    hasBGM: false,
    video: '../videos/single_leg_deadlift.mp4',
    images: [],
  },
];

export function getExercise(id) {
  return exercises.find(e => e.id === id);
}

export function getTrainableExercises() {
  return exercises.filter(e => e.mode !== null);
}

export function getDailyExercises() {
  return exercises.filter(e => e.daily !== false);
}
